services:
  prep:
    restart: no
    image: ghcr.io/justereseau/omni_etcd_backup:9e7f2d8a1fe538d5564231bd33c7a7014a0c3945
    environment:
      ETCD_DIR: /etcd
      GPG_PRIVATE_KEY: /gpg/private.pem
    env_file:
      - path: ./configs/restore.env
        required: true
      - path: ./configs/restore.override.env
        required: false
    entrypoint: /scripts/restore.sh
    volumes:
      - ./data/etcd:/etcd
      - ./gpg/bk.key:/gpg/private.pem:ro

  bk:
    # To add to cron: docker compose --project-directory /home/lmaurice/omni -f docker-compose.yml -f docker-compose-actions.yml up bk --build
    restart: no
    image: ghcr.io/justereseau/omni_etcd_backup:9e7f2d8a1fe538d5564231bd33c7a7014a0c3945
    environment:
      GPG_PUBLIC_KEY: /gpg/public.pem
      ETCD_ENDPOINT: http://omni:2379
    env_file:
      - path: ./configs/backup.env
        required: true
      - path: ./configs/backup.override.env
        required: false
    volumes:
      - ./data/etcd-backup:/backups
      - ./gpg/bk.pub:/gpg/public.pem:ro
