services:
  # httpd:
  #   image: lipanski/docker-static-website:latest
  #   restart: unless-stopped
  #   command: [ "/busybox-httpd", "-f", "-v", "-p", "8080" ]
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./data/pxe-assets:/home/static:ro

  # tftpd:
  #   build: tftpd
  #   restart: unless-stopped
  #   command:
  #     - --tftp.root-dir=/data
  #   ports:
  #     - 69:69/udp
  #   volumes:
  #     - ./data/pxe-assets:/data:ro

  omni:
    image: ghcr.io/siderolabs/omni:v0.48.1
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 443:443 # Sidero UI
      - 8090:8090 # API Endpoint ?
      - 8100:8100 # Kubernetes Proxy
      - 50180:50180/udp # Wireguard
      - 50180:50180/tcp # Wireguard
      - 2122:2122 # Prometheus Metrics
    volumes:
      - ./data/etcd:/_out/etcd:rw
      - ./gpg/omni.asc:/omni.asc:ro
      - /etc/letsencrypt/live/omni.lab.djls.space/fullchain.pem:/tls.crt:ro
      - /etc/letsencrypt/live/omni.lab.djls.space/privkey.pem:/tls.key:ro
    command:
      - --account-id=37913815-f635-4327-9137-d61095852854
      - --name=onprem-omni
      - --advertised-kubernetes-proxy-url=https://omni.lab.djls.space:8100
      - --k8s-proxy-bind-addr=0.0.0.0:8100
      - --advertised-api-url=https://omni.lab.djls.space
      - --bind-addr=0.0.0.0:443
      - --cert=/tls.crt
      - --key=/tls.key
      - --private-key-source=file:///omni.asc
      - --event-sink-port=8091

      - --siderolink-api-advertised-url=https://omni.lab.djls.space:8090
      - --machine-api-bind-addr=0.0.0.0:8090
      - --machine-api-cert=/tls.crt
      - --machine-api-key=/tls.key

      - --siderolink-wireguard-advertised-addr=10.250.11.10:50180
      - --siderolink-wireguard-bind-addr=0.0.0.0:50180

      - --auth-auth0-enabled=true
      - --auth-auth0-domain=justereseau.ca.auth0.com
      - --auth-auth0-client-id=gdfQSEGmwTyNaovAtlqPF0TVSF93BSjZ
      - --initial-users=lucas@djls.io

      - --etcd-embedded=true
      - --etcd-endpoints=http://0.0.0.0:2379
      - --etcd-backup-max-interval=24h0m0s
      - --etcd-backup-min-interval=1h0m0s
      - --etcd-backup-tick-interval=1m0s

      - --workload-proxying-enabled=true
      - --workload-proxying-subdomain=op
